image: gcc

    
stages:
    - build
    - test

build:
    stage: build
    before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - apt-get install --yes libgtest-dev
    script:
    - echo "Build Stage"
    - mkdir -p build
    - cd build
    - cmake ..
    - make cache 
    - make cachetest
    artifacts:
        paths:
        - build/

test:
  stage: test
  script:
    - echo "Test Stage"
    - cd build
    - ./test/cachetest